name: appliances_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^14.0.2
  geocoding: ^2.0.0
  google_maps_flutter: ^2.5.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.3.1
  provider: ^6.1.1
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.4
  country_picker: ^2.0.23
  phone_otp_verification: ^1.0.3
  flutter_otp_text_field: ^1.5.1+1
  app_links: ^6.4.1
  webview_flutter: ^4.13.0
  vietmap_flutter_gl: ^4.1.0
  vietmap_flutter_plugin: ^0.5.2
  firebase_app_check: ^0.4.1+2
  timeago: ^3.6.1
  carousel_slider: ^5.0.0
  socket_io_client: ^2.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  vietmap_flutter_gl_web:
    path: packages/vietmap_flutter_gl_web

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - assets/banner/
    - assets/images/restaurant_bk.png
